@ __config _INTRC_OSC_NOCLKOUT & _WDT_OFF & _LVP_OFF & _CP_ON & _PWRTE_ON & _MCLRE_ON & _BODEN_OFF
DEFINE OSC 4
CMCON      = 7
OPTION_REG = %00000000

TRISA = %10111111
TRISB = %01000000

BILGI   VAR BYTE
BILGI   = 0
FREKANS VAR WORD
FREKANS = 8270
DURUM   VAR BYTE
DURUM   = 0

PORTA = 0
PORTB = 0

BASLA:
    FREQOUT PORTA.6, 15, FREKANS
    COUNT   PORTB.7, 15, BILGI

    IF BILGI >= 124 THEN
        PORTB.0 = 1
        DURUM   = 1
    ELSE
        PORTB.0 = 0
        DURUM   = 0
    ENDIF
GOTO BASLA
END
